### ISSUE TITLE
Planned Breaking changes for version 2.0.0

### ISSUE THREAD

**Issue by devsnd** [devsnd/tinytag#98]
This is a record of planned breaking changes for a major version change

 - [x] The `track` and `track_total` field should return integers instead of 
 - [x] The `disc` and `disc_total` fields should return integers instead of strings
 - [x] Mark TinyTag subclasses as private
 - [x] Mark `audio_offset` field as private
 - [x] Move `composer` field to `extra` dict
 - [x] TinyTagException should not inherit LookupError
 - [x] Dropping python 2.7 support
   e.g. usage of `unicode` https://github.com/devsnd/tinytag/blob/master/tinytag/tinytag.py#L211
   `float()` casting https://github.com/devsnd/tinytag/blob/master/tinytag/tinytag.py#L336
   use `bytes.decode` instead of `codecs` https://github.com/devsnd/tinytag/blob/master/tinytag/tinytag.py#L631

**Comment by devsnd** [comment]
Question from mathiascode: Should we keep exposing MP3, OGG etc interfaces directly, or only the TinyTag interface in the 2.0 release?

**Comment by mathiascode** [comment]
@devsnd I think we should mark the `audio_offset` variable as private. It's not available/used in several of our formats, and not very useful as-is without an additional variable like `audio_size`.

**Comment by mathiascode** [comment]
Useful tool for upgrading syntax: https://github.com/asottile/pyupgrade

**Comment by mathiascode** [comment]
Updated documentation for 2.0.0 is available here: https://github.com/mathiascode/tinytag/blob/2.0.0-docs/README.md

Let me know if something is unclear, missing or incorrect, and I'll make improvements before the final release.
